### PR TITLE
Support local xz file

### PR DESCRIPTION
**Pull request by d3m3vilurr**
`$VITASDK/packages` is [vitasdk/packages](https://github.com/vitasdk/packages)

this patch can allow like this action

```
cd $VITASDK/packages/taihen
vita-makepkg
vdpm taihen # install local built package
```

### CODE REVIEW

**Comment by xyzz** [comment]
I think a better approach is check if file exists, then untar it if it does. Then you just run it like `vdpm abc.tar.xz`. In this case it does not require a specific layout (packages cloned inside VITASDK)

**Comment by d3m3vilurr** [comment]
Hm... or this action move to vita-makepkg

I thought vdpm is `vita dev package manager`, so i think that is `apt` not `dpkg`.
And this rule is already include vdpm, they try download pacage from remote repo, then install(untar).
But vdpm not know all package informations, ports and ports clone sync that info from remote using rsync, svn or git and locate that info directory in `/usr`
So I thought `packages` can locate in `$VITASDK`.

**Comment by xyzz** [comment]
Right now the idea's that every user will have vdpm installed, but very few users will have vita-makepkg installed. So I think it's better to have local .tar.xz install in vdpm, as sometimes you might want to give somebody a package and tell them to install it.

I don't understand why you are comparing it with apt and dpkg, on archlinux for example, pacman can do both local package install and remote. I don't see any problem with a tool called `package manager` installing local packages as well as remote - they could eventually have metadata inside and it could eventually be managed in a proper way by `vdpm`. But for now it's a simple untar.

**Comment by d3m3vilurr** [comment]
well, cuz I did't use arch & pacman. I just used portage on gentoo & funtoo and apt on debian & ubuntu.
I thought package manager will do;

1. check dependensies
2. then, can resolve this.
3. manage installed packages

I think, probably pacman support this.

at the first looks `packages`, I was thought that repo looks ports like tree.
but you said it's not. so I guess we need another approach for sharing package list...

and ok, I'll change to support xz file path. :)
https://wiki.archlinux.org/index.php/pacman#Additional_commands you said second case, right?

**Pull request merged**
