### PR TITLE
Add missing packages

### PR DESCRIPTION
**Pull request by SonicMastr**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
when i see the similar issues like this, almost times, i merged.
but i don't think we need to add every packages into default install script.
devs can install packages using `vdpm ${package_name}` in their dev box.
(for example, every linux distributions don't install every packages at install time. they just install very small package sets for making their environments)

so, you devs, do you really need this patch? if that, i'll merge it.

**Comment by joel16** [comment]
Well vitagl requires SceShaccCgExt now.

**Comment by d3m3vilurr** [comment]
oh... vitagl has SceShaccCgExt in depencencies. isn't it install automatically?
maybe that is bug of vdpm.

**Comment by isage** [comment]
Dependencies work only for building. vdpm is simply `curl | tar`

**Comment by d3m3vilurr** [comment]
huh...i confused vita-makepkg... so we have to make dependency part and install the vitainstall files to somewhere like `$VITASDK/src`...
maybe making pacman repo is simpler than it. :'(

**Pull request merged**
